### ISSUE TITLE
custom sql loading fails to re-execute during syncdb

### ISSUE THREAD

**Issue by slinkp** [openplans/openblock#108]
I think this custom sql that is now a post-sync call fails if you run syncdb again

```
(openblock)ltucker:src ltucker$ django-admin.py syncdb
Loading extra post-syncdb SQL data from '/Users/ltucker/devel/openblock/src/openblock/ebpub/ebpub/db/sql/location_post_syncdb.sql'
Failed to install post-syncdb SQL file '/Users/ltucker/devel/openblock/src/openblock/ebpub/ebpub/db/sql/location_post_syncdb.sql': trigger "set_loc_area" for relation "db_location" already exists

Traceback (most recent call last):
  File "/Users/ltucker/devel/openblock/src/openblock/ebpub/ebpub/db/management.py", line 55, in location_post_syncdb_callback
    cursor.execute(sql)
  File "/Users/ltucker/devel/openblock/src/django/django/db/backends/util.py", line 15, in execute
    return self.cursor.execute(sql, params)
  File "/Users/ltucker/devel/openblock/src/django/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
DatabaseError: trigger "set_loc_area" for relation "db_location" already exists
```

**Comment by slinkp** [comment]
obsolete now that we're using South.

**Comment by slinkp** [comment]
Ticket imported from Trac:
 http://developer.openblockproject.org/ticket/108
Reported by: ltucker
