### ISSUE TITLE
Map layers broken on "big map"

### ISSUE THREAD

**Issue by slinkp** [openplans/openblock#268]
The richmaps page throws exceptions on the back end when you click on an item type in the layer selector widget:

```
[Mon Feb 27 16:09:51 2012] [error] ERROR base: Internal Server Error: /maps/items.json
[Mon Feb 27 16:09:52 2012] [error] Traceback (most recent call last):
[Mon Feb 27 16:09:52 2012] [error]   File "/var/www/demo.openblockproject.org/current/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
[Mon Feb 27 16:09:52 2012] [error]     response = callback(request, *callback_args, **callback_kwargs)
[Mon Feb 27 16:09:52 2012] [error]   File "/var/www/demo.openblockproject.org/builds/20110815/src/openblock/ebpub/ebpub/richmaps/views.py", line 421, in map_items_json
[Mon Feb 27 16:09:52 2012] [error]     items, params = build_item_query(_copy_nomulti(request.GET))
[Mon Feb 27 16:09:52 2012] [error]   File "/var/www/demo.openblockproject.org/builds/20110815/src/openblock/ebpub/ebpub/openblockapi/itemquery.py", line 58, in build_item_query
[Mon Feb 27 16:09:52 2012] [error]     params = _copy_nomulti(request.GET)
[Mon Feb 27 16:09:52 2012] [error] AttributeError: 'dict' object has no attribute 'GET'

```

**Comment by slinkp** [comment]
Ticket imported from Trac:
 http://developer.openblockproject.org/ticket/275
Reported by: slinkp
